using System;
using System.Collections.Generic;
using System.Text;

namespace DBSBankComman.Querie
{
    public class Queries
    {
        public static string push_advice = "INSERT INTO BLUESTARTF_PROD.push_advice(msgId,orgId,timeStamp,channelId,ctry,documentDescription,documentName,customerReference,bankReference,encodedFile)values(:msgId,:orgId,:timeStamp,:channelId,:ctry,:documentDescription,:documentName,:customerReference,:bankReference,:encodedFile)";
        public static string lc_ack = "INSERT INTO BLUESTARTF_PROD.ACKRESPONSE(msgId,orgId,timeStamp,channelId,noOfDocAttached,ctry,responseType,txnRefId,txnStatus,txnRejectCode,txnStatusDescription,status,code,description,attachmentRef)values(:msgId,:orgId,:timeStamp,:channelId,:noOfDocAttached,:ctry,:responseType,:txnRefId,:txnStatus,:txnRejectCode,:txnStatusDescription,:status,:code,:description,:attachmentRef)";
        public static string locpush = "INSERT INTO BLUESTARTF_PROD.letterofcredit(msgId,orgId,TimeStamp,channelId,ctry,noOfDocAttached,txnType,accountNumber,ccy,customerReference,applicantContactName,applicantContactNumber,thirdPartyName,thirdPartyAddress,beneName,beneAddress, beneCountry,beneContactName,beneContactNumber,advisingBank,advisingBankAddress,advisingBankSwiftCode,sendVia,expiryDate,expiryCountry,expiryPlace,lcType, lcCcy,lcAmount,localLcAmtIs,tolCrAmtGoodsQuanPlus,tolCrAmtGoodsQuanMinus,creditAvailableWith,creditAvailableWithOthersName,creditAvailableWithOthersAdd,creditAvailableBy,draftDrawnOn,tenor,tenorDays,tenorPhrase,tenorPhraseOthers,tenorPhraseFxdMat,paymentDetails,creditTransferable,confirmationRequired,confirmationCharges,confirmingBank,confirmingBankAddress,goodsDescription,placeOfReceipt,portOfLoading,portOfDischarge,placeOfDelivery,partialShipmentAllowed,transhipmentAllowed,latestShipmentDate,shipmentPeriod,presentationPeriod,presentationPeriodFrom,presentationPeriodOth,shippingTerms,insuranceBy,buyerInsuranceDetails,coverNoteDetails,transportDocType,freight,freightOthers,totalOriginals,originalsRequired,copiesRequired,consignedTo,consignedToOthers,notifyParty,docRequired,insuranceDocs,additionalConditions,specialConditionBene,specialConditionAdv,charges,chargesOthers,chargesAccountNo,chargesAccountCcy,specialInstruction, financeRequired,financeCurrency,forwardContractNumber,typeOfDocument,noOfSets,noOfOriginal,noOfCopies)values(:msgId,:orgId,:TimeStamp,:channelId,:ctry,:noOfDocAttached,:txnType,:accountNumber,:ccy,:customerReference,:applicantContactName,:applicantContactNumber,:thirdPartyName,:thirdPartyAddress,:beneName,:beneAddress,: beneCountry,:beneContactName,:beneContactNumber,:advisingBank,:advisingBankAddress,:advisingBankSwiftCode,:sendVia,:expiryDate,:expiryCountry,:expiryPlace,:lcType,:lcCcy,:lcAmount,:localLcAmtIs,:tolCrAmtGoodsQuanPlus,:tolCrAmtGoodsQuanMinus,:creditAvailableWith,:creditAvailableWithOthersName,:creditAvailableWithOthersAdd,:creditAvailableBy,:draftDrawnOn,:tenor,:tenorDays,:tenorPhrase,:tenorPhraseOthers,:tenorPhraseFxdMat,:paymentDetails,:creditTransferable,:confirmationRequired,:confirmationCharges,:confirmingBank,:confirmingBankAddress,:goodsDescription,:placeOfReceipt,:portOfLoading,:portOfDischarge,:placeOfDelivery,:partialShipmentAllowed,:transhipmentAllowed,:latestShipmentDate,:shipmentPeriod,:presentationPeriod,:presentationPeriodFrom,:presentationPeriodOth,:shippingTerms,:insuranceBy,:buyerInsuranceDetails,:coverNoteDetails,:transportDocType,:freight,:freightOthers,:totalOriginals,:originalsRequired,:copiesRequired,:consignedTo,:consignedToOthers,:notifyParty,:docRequired,:insuranceDocs,:additionalConditions,:specialConditionBene,:specialConditionAdv,:charges,:chargesOthers,:chargesAccountNo,:chargesAccountCcy,:specialInstruction, :financeRequired,:financeCurrency,:forwardContractNumber,:typeOfDocument,:noOfSets,:noOfOriginal,:noOfCopies)";
        public static string locget = "select msgId,rgId,TimeStamp,channelId,ctry,noOfDocAttached,txnType,accountNumber,ccy,customerReference,applicantContactName,applicantContactNumber,thirdPartyName,thirdPartyAddress,beneName,beneAddress, beneCountry,beneContactName,beneContactNumber,advisingBank,advisingBankAddress,advisingBankSwiftCode,sendVia,expiryDate,expiryCountry,expiryPlace,lcType, lcCcy,lcAmount,localLcAmtIs,tolCrAmtGoodsQuanPlus,tolCrAmtGoodsQuanMinus,creditAvailableWith,creditAvailableWithOthersName,creditAvailableWithOthersAdd,creditAvailableBy,draftDrawnOn,tenor,tenorDays,tenorPhrase,tenorPhraseOthers,tenorPhraseFxdMat,paymentDetails,creditTransferable,confirmationRequired,confirmationCharges,confirmingBank,confirmingBankAddress,goodsDescription,placeOfReceipt,portOfLoading,portOfDischarge,placeOfDelivery,partialShipmentAllowed,transhipmentAllowed,latestShipmentDate,shipmentPeriod,presentationPeriod,presentationPeriodFrom,presentationPeriodOth,shippingTerms,insuranceBy,buyerInsuranceDetails,coverNoteDetails,transportDocType,freight,freightOthers,totalOriginals,originalsRequired,copiesRequired,consignedTo,consignedToOthers,notifyParty,docRequired,insuranceDocs,additionalConditions,specialConditionBene,specialConditionAdv,charges,chargesOthers,chargesAccountNo,chargesAccountCcy,specialInstruction, financeRequired,financeCurrency,forwardContractNumber,typeOfDocument,noOfSets,noOfOriginal,noOfCopies from BLUESTARTF_PROD.letterofcredit where PROCESSSTATUS=12400002";
        public static string UnParkingUpdateQuery = "UPDATE BLUESTARTF_PROD.letterofcredit SET PROCESSSTATUS=12400001 WHERE PROCESSSTATUS = 12400002";
        public static string DocQuery = "select DOCUMENT_IMAGE, DOCUMENT_TYPE, DOCUMENT_NAME from BLUESTARTF_PROD.letterofcreditDocs where DOCUMENT_NAME = '811-01-0128639.pdf' ";
    }
}
