using System;
using System.Collections.Generic;
using System.Text;

namespace DBSBankComman.Querie
{
    public class Queries
    {
        public static string DOC = "select  IMAG_DOCUMENT_NAME ,IMAG_DOCUMENT_IMAGE  from BLUESTARTF_PROD.TFTRAN101 WHERE IMAG_DOCUMENT_NAME='Schema user.txt'";
        public static string push_advice = "INSERT INTO BLUESTARTF_PROD.push_advice(msgId,orgId,timeStamp,channelId,ctry,documentDescription,documentName,customerReference,bankReference,encodedFile)values(:msgId,:orgId,:timeStamp,:channelId,:ctry,:documentDescription,:documentName,:customerReference,:bankReference,:encodedFile)";
        public static string lc_ack = "INSERT INTO BLUESTARTF_PROD.TradeLC_ACK(msgId,orgId,timeStamp,channelId,noOfDocAttached,ctry,responseType,txnRefId,txnStatus,txnRejectCode,txnStatusDescription,attachmentRef,imexReference,customerReference,status,code,description)values(:msgId,:orgId,:timeStamp,:channelId,:noOfDocAttached,:ctry,:responseType,:txnRefId,:txnStatus,:txnRejectCode,:txnStatusDescription,:attachmentRef,:imexReference,:customerReference,:status,:code,:description)";
        public static string locpush = "INSERT INTO BLUESTARTF_PROD.letterofcredit(msgId,orgId,TimeStamp,channelId,ctry,noOfDocAttached,txnType,accountNumber,ccy,customerReference,applicantContactName,applicantContactNumber,thirdPartyName,thirdPartyAddress,beneName,beneAddress, beneCountry,beneContactName,beneContactNumber,advisingBank,advisingBankAddress,advisingBankSwiftCode,sendVia,expiryDate,expiryCountry,expiryPlace,lcType, lcCcy,lcAmount,localLcAmtIs,tolCrAmtGoodsQuanPlus,tolCrAmtGoodsQuanMinus,creditAvailableWith,creditAvailableWithOthersName,creditAvailableWithOthersAdd,creditAvailableBy,draftDrawnOn,tenor,tenorDays,tenorPhrase,tenorPhraseOthers,tenorPhraseFxdMat,paymentDetails,creditTransferable,confirmationRequired,confirmationCharges,confirmingBank,confirmingBankAddress,goodsDescription,placeOfReceipt,portOfLoading,portOfDischarge,placeOfDelivery,partialShipmentAllowed,transhipmentAllowed,latestShipmentDate,shipmentPeriod,presentationPeriod,presentationPeriodFrom,presentationPeriodOth,shippingTerms,insuranceBy,buyerInsuranceDetails,coverNoteDetails,transportDocType,freight,freightOthers,totalOriginals,originalsRequired,copiesRequired,consignedTo,consignedToOthers,notifyParty,docRequired,insuranceDocs,additionalConditions,specialConditionBene,specialConditionAdv,charges,chargesOthers,chargesAccountNo,chargesAccountCcy,specialInstruction, financeRequired,financeCurrency,forwardContractNumber,typeOfDocument,noOfSets,noOfOriginal,noOfCopies)values(:msgId,:orgId,:TimeStamp,:channelId,:ctry,:noOfDocAttached,:txnType,:accountNumber,:ccy,:customerReference,:applicantContactName,:applicantContactNumber,:thirdPartyName,:thirdPartyAddress,:beneName,:beneAddress,: beneCountry,:beneContactName,:beneContactNumber,:advisingBank,:advisingBankAddress,:advisingBankSwiftCode,:sendVia,:expiryDate,:expiryCountry,:expiryPlace,:lcType,:lcCcy,:lcAmount,:localLcAmtIs,:tolCrAmtGoodsQuanPlus,:tolCrAmtGoodsQuanMinus,:creditAvailableWith,:creditAvailableWithOthersName,:creditAvailableWithOthersAdd,:creditAvailableBy,:draftDrawnOn,:tenor,:tenorDays,:tenorPhrase,:tenorPhraseOthers,:tenorPhraseFxdMat,:paymentDetails,:creditTransferable,:confirmationRequired,:confirmationCharges,:confirmingBank,:confirmingBankAddress,:goodsDescription,:placeOfReceipt,:portOfLoading,:portOfDischarge,:placeOfDelivery,:partialShipmentAllowed,:transhipmentAllowed,:latestShipmentDate,:shipmentPeriod,:presentationPeriod,:presentationPeriodFrom,:presentationPeriodOth,:shippingTerms,:insuranceBy,:buyerInsuranceDetails,:coverNoteDetails,:transportDocType,:freight,:freightOthers,:totalOriginals,:originalsRequired,:copiesRequired,:consignedTo,:consignedToOthers,:notifyParty,:docRequired,:insuranceDocs,:additionalConditions,:specialConditionBene,:specialConditionAdv,:charges,:chargesOthers,:chargesAccountNo,:chargesAccountCcy,:specialInstruction, :financeRequired,:financeCurrency,:forwardContractNumber,:typeOfDocument,:noOfSets,:noOfOriginal,:noOfCopies)";
        public static string locget = "select msgId,rgId,TimeStamp,channelId,ctry,noOfDocAttached,txnType,accountNumber,ccy,customerReference,applicantContactName,applicantContactNumber,thirdPartyName,thirdPartyAddress,beneName,beneAddress, beneCountry,beneContactName,replace(beneContactNumber,' ','') beneContactNumber ,advisingBank,advisingBankAddress,advisingBankSwiftCode,sendVia,expiryDate,expiryCountry,lcType, lcCcy,expiryPlace,lcAmount,localLcAmtIs,tolCrAmtGoodsQuanPlus,tolCrAmtGoodsQuanMinus,creditAvailableWith,creditAvailableWithOthersName,creditAvailableWithOthersAdd,creditAvailableBy,draftDrawnOn,tenor,tenorDays,tenorPhrase,tenorPhraseOthers,tenorPhraseFxdMat,paymentDetails,creditTransferable,confirmationRequired,confirmationCharges,confirmingBank,confirmingBankAddress,goodsDescription,placeOfReceipt,portOfLoading,portOfDischarge,placeOfDelivery,partialShipmentAllowed,transhipmentAllowed,latestShipmentDate,shipmentPeriod,presentationPeriod,presentationPeriodFrom,presentationPeriodOth,shippingTerms,insuranceBy,buyerInsuranceDetails,coverNoteDetails,transportDocType,freight,freightOthers,totalOriginals,originalsRequired,copiesRequired,consignedTo,consignedToOthers,notifyParty,docRequired,insuranceDocs,additionalConditions,specialConditionBene,specialConditionAdv,charges,chargesAccountNo,chargesOthers,specialInstruction, financeRequired,financeCurrency,forwardContractNumber,chargesAccountCcy,typeOfDocument,noOfSets,noOfOriginal,noOfCopies from BLUESTARTF_PROD.letterofcredit where PROCESSSTATUS=12400002 and ROWNUM <=1";
        public static string UpdateLCQuery = "UPDATE BLUESTARTF_PROD.letterofcredit SET PROCESSSTATUS=12400001 WHERE msgId= ";
        public static string LC_Doc_Upload = "select msgId,rgId,timeStamp,channelId,ctry,attachmentRef from BLUESTARTF_PROD.letterofcredit WHERE msgId=";
        public static string LC_NUM = "select LCNUMBER from BLUESTARTF_PROD.letterofcredit WHERE msgId = ";

        //replace(beneContactNumber,' ','') 
        public static string LC_ACK1_failed = "UPDATE BLUESTARTF_PROD.letterofcredit SET responseType =:responseType ,txnStatus=:txnStatus ,txnStatusDescription =:txnStatusDescription WHERE msgId= ";
        public static string LC_ACK2_Sucess = "UPDATE BLUESTARTF_PROD.letterofcredit SET responseType =:responseType ,txnStatus=:txnStatus ,txnStatusDescription =:txnStatusDescription ,attachmentRef =:attachmentRef WHERE msgId= ";


        public static string LC_ACK1 = "UPDATE BLUESTARTF_PROD.letterofcredit SET code=";
    }
}
